name: deploy ht
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: see pods
        run: kubectl config get-contexts 
      - name: see pods
        run: kubectl config current-context 
      - name: install ht
        run: ./kubernetes/hypertrace.sh install
      - name: see pods
        run: kubectl get pods -n hypertrace
      - name: see services
        run: kubectl get services -n hypertrace       
