name: Snyk main
on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened, closed]

jobs:
  snyk-main:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Running script
      run: ./.github/workflows/test.sh

