name: Snyk main
on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened, closed]
  release:
    types:
      - created
    

jobs:
  snyk-main:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest stable Octoprint
        id: kafka
        uses: oprypin/find-latest-tag@v1
        with:
          repository: hypertrace/kafka
      - uses: actions/checkout@v2
      - name: validate charts
        run: ./.github/workflows/release.sh
        env: 
          kafka_version: ${{ steps.kafka.outputs.tag }}
