name: Snyk main
on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened, closed]
  release:
    types:
      - created
    

jobs:
  snyk-main:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest stable Octoprint
        id: kafka
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: hypertrace
          repo: kafka
          excludes: prerelease,draft 
      - uses: actions/checkout@v2
      - name: validate charts
        run: ./.github/workflows/release.sh
        env: 
          kafka_version: ${{ steps.kafka.outputs.release }}
