name: Snyk main
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  snyk-main:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name = github.repository
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Running script
      run: ./.github/workflows/test.sh

