name: Snyk main
on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened, closed]

jobs:
  snyk-main:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Running script
      run: ./.github/workflows/test.sh
    - name: Option1 for gettign branch
      run: ./.github/workflows/test.sh
      env:
        GITHUB_BRANCh_1: ${{ github.ref }}
    - name: Options2 for getting 
      run: ./.github/workflows/test.sh
      env:
        GITHUB_BRANCH_2: $(echo ${GITHUB_REF#refs/heads/}) 

