name: Snyk main
on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened, closed]
  release:
    types:
      - created
    

jobs:
  snyk-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Option1 for gettign branch
      if: github.event_name == 'push' 
      run: | 
        BRANCH="${GITHUB_REF#refs/heads/}"
        echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
        ./.github/workflows/test.sh
    - name: Running script
      run: ./.github/workflows/test.sh

