name: Snyk Container
on:
  push:
    branches:
      - main
  pull_request:
     branches: 
      - main
  pull_request_target:
    branches:
      - ref/pull/*
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Running script
      run: ./.github/workflows/test.sh
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
