name: get latest data services
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    

jobs:
  get-latest-releases:
    runs-on: ubuntu-20.04
    steps:
      - name: Get latest stable 
        id: kafka
        uses: oprypin/find-latest-tag@v1
        with:
          repository: hypertrace/kafka
      - run: echo "latest stable release ${{ steps.kafka.outputs.tag }}"

      - name: Get latest stable 
        id: zookeeper
        uses: oprypin/find-latest-tag@v1
        with:
          repository: hypertrace/zookeeper
      - run: echo "latest stable release ${{ steps.zookeeper.outputs.tag }}"

      - name: Get latest stable 
        id: pinot
        uses: oprypin/find-latest-tag@v1
        with:
          repository: hypertrace/pinot
      - run: echo "latest stable release ${{ steps.pinot.outputs.tag }}"

      - name: Get latest stable 
        id: schema-registry
        uses: oprypin/find-latest-tag@v1
        with:
          repository: hypertrace/schema-registry
      - run: echo "latest stable release ${{ steps.schema-registry.outputs.tag }}"

      - name: Get latest stable 
        id: mongodb
        uses: oprypin/find-latest-tag@v1
        with:
          repository: hypertrace/mongodb
      - run: echo "latest stable release ${{ steps.mongodb.outputs.tag }}"

      - uses: actions/checkout@v2

      - name: create charts 
        run: ./.github/workflows/create-charts.sh
        env: 
          kafka_version: ${{ steps.kafka.outputs.tag }}
          pinot_version: ${{ steps.pinot.outputs.tag }}
          schema_registry_version: ${{ steps.schema-registry.outputs.tag }}
          mongodb_version: ${{ steps.mongodb.outputs.tag }}
          zookeeper_version: ${{ steps.zookeeper.outputs.tag }}