name: get latest data services
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-latest-releases:
    runs-on: ubuntu-20.04
    steps:
      - name: Get latest stable 
        id: kafka
        uses: oprypin/find-latest-tag@v1
        with:
          repository: hypertrace/kafka
      - run: echo "latest stable release ${{ steps.kafka.outputs.tag }}"

      - name: Get latest stable 
        id: zookeeper
        uses: oprypin/find-latest-tag@v1
        with:
          repository: hypertrace/zookeeper
      - run: echo "latest stable release ${{ steps.zookeeper.outputs.tag }}"

      - name: Get latest stable 
        id: pinot
        uses: oprypin/find-latest-tag@v1
        with:
          repository: hypertrace/pinot
      - run: echo "latest stable release ${{ steps.pinot.outputs.tag }}"

      - name: Get latest stable 
        id: schema-registry
        uses: oprypin/find-latest-tag@v1
        with:
          repository: hypertrace/schema-registry
      - run: echo "latest stable release ${{ steps.schema-registry.outputs.tag }}"

      - name: Get latest stable 
        id: mongodb
        uses: oprypin/find-latest-tag@v1
        with:
          repository: hypertrace/mongodb
      - run: echo "latest stable release ${{ steps.mongodb.outputs.tag }}"

      - uses: actions/checkout@v2

      - name: create charts 
        run: ./.github/workflows/create-charts.sh
        env: 
          kafka_version: ${{ steps.kafka.outputs.tag }}
          pinot_version: ${{ steps.pinot.outputs.tag }}
          schema_registry_version: ${{ steps.schema-registry.outputs.tag }}
          mongodb_version: ${{ steps.mongodb.outputs.tag }}
          zookeeper_version: ${{ steps.zookeeper.outputs.tag }}

      - name: create charts 
        run: |
          git add . 
          git branch -m "release-charts"
          git commit -m "Updated Repository data"
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: peter-evans
          reviewers: peter-evans
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false
